[package]
name = "api-docs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glob = "0.3.1"
jsdoc = "0.103.12"
regex = "1.8.4"
swc_common = "0.31.12"
